version: "3.7"
services:
  api.gouv.fr:
    image: jekyll/jekyll:3.7
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - vendor:/usr/local/bundle
    command: jekyll serve

volumes:
  vendor:
